sudo: false
language: python

services:
  - elasticsearch

addons:
  apt:
    sources:
      antiword
      pdftohtml

install:
  - CFLAGS="-O0" pip install -r requirements.txt
  - pip freeze
  - sed -r -e "s,(ZAH_DB_USER:) 'za-hansard',\\1 'postgres'," conf/general.yml-example > conf/general.yml

before_script:
  - psql -c 'create database "za-hansard";' -U postgres
  - ./manage.py migrate --noinput
  -  pdftohtml -v || true

script:
  - ./manage.py test

# report results in IRC
# notifications:
#   irc: "irc.mysociety.org#pmo"
#   use_notice: true
#   skip_join: true
