language: python

addons:
  postgresql: "9.6"
  apt:
    packages:
    # This is needed so that pg_config works for psycopg2's version detection
    - postgresql-server-dev-9.6

services:
  - elasticsearch

install:
  - sudo apt-get update -qq
  - cat conf/packages | sed -r -e 's,#.*,,' | xargs sudo apt-get install -qq
  - CFLAGS="-O0" pip install -r requirements.txt
  - pip freeze
  - sed -r -e "s,(ZAH_DB_USER:) 'za-hansard',\\1 'postgres'," conf/general.yml-example > conf/general.yml

before_script:
  - psql -c 'create database "za-hansard";' -U postgres
  - ./manage.py migrate --noinput
  -  pdftohtml -v || true

script:
  - pytest

# report results in IRC
# notifications:
#   irc: "irc.mysociety.org#pmo"
#   use_notice: true
#   skip_join: true
